### ISSUE TITLE
pyperclip EOF error

### ISSUE THREAD

**Issue by SwiftGodDev** [Zeta36/chess-alpha-zero#102]
Traceback (most recent call last):
  File "src/chess_zero/run.py", line 20, in <module>
    manager.start()
  File "src/chess_zero/manager.py", line 64, in start
    return self_play.start(config)
  File "src/chess_zero/worker/self_play.py", line 25, in start
    return SelfPlayWorker(config).start()
  File "src/chess_zero/worker/self_play.py", line 69, in start
    pretty_print(env, ("current_model", "current_model"))
  File "src/chess_zero/lib/data_helper.py", line 26, in pretty_print
    pyperclip.copy(env.board.fen())
  File "/usr/local/lib/python3.6/dist-packages/pyperclip/__init__.py", line 659, in lazy_load_stub_copy
    return copy(text)
  File "/usr/local/lib/python3.6/dist-packages/pyperclip/__init__.py", line 336, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error 
Exception in thread prediction_worker:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "src/chess_zero/agent/api_chess.py", line 63, in _predict_batch_worker
    data.append(pipe.recv())
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

**Comment by SwiftGodDev** [comment]
It works for one game then this error occurs
