### ISSUE TITLE
Problem with installl

### ISSUE THREAD

**Issue by nicolasgerardo** [Zeta36/chess-alpha-zero#23]
Hi everyone, i don't know how to install the software, always appearme this:

File "src/chess_zero/run.py", line 4, in <module>
    from dotenv import load_dotenv, find_dotenv
ModuleNotFoundError: No module named 'dotenv'

I need your help!! 
Thanks, Nicolás

**Comment by ddugovic** [comment]
Try `pip3 install python-dotenv` I think?

**Comment by nicolasgerardo** [comment]
Nothing, i think that i don't know how install this, could yo help me ?

**Comment by Akababa** [comment]
What does it say when you run that pip3 command?

**Comment by nicolasgerardo** [comment]
C:\Users\Admin\OneDrive\Desktop\chess-alpha-zero-master>pip3 install python-dotenv
"pip3" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
it says that "pip3"  the external or internal command isn't recognized.
I try to install this with anaconda in windows, i need to install in linux?

**Comment by Akababa** [comment]
you might have an older version of python, you need 3.6 for this project.

What does pip --version say?

**Comment by nicolasgerardo** [comment]
C:\Users\nicol\OneDrive\Desktop\chess-alpha-zero-master>python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by Akababa** [comment]
Oh okay, just `pip install python-dotenv`

**Comment by nicolasgerardo** [comment]
![image](https://user-images.githubusercontent.com/34495354/33975179-fee601fe-e05a-11e7-8f5c-26545704ad03.png)

**Comment by jeldis** [comment]
Hi @nicolasgerardo I think there are some packages that won't work on Windows, if you what to test it, is better you install it on linux OS, o Mac.

Best regards

**Comment by nicolasgerardo** [comment]
Hi @jeldis , I've been installing from ubuntu, but it's impossible, could you help me step by step?

**Comment by waleedis** [comment]
I am having problem to execute chess alpha zero.

Error Begin:
(check_tensor) C:\Users\m.waleed\Documents\chess-alpha-zero\src\chess_zero>run.p
y uci
go
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\te
nsorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\importlib\__init
__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\te
nsorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\te
nsorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\te
nsorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\importlib\__init
__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\m.waleed\Documents\chess-alpha-zero\src\chess_zero\run.py", lin
e 20, in <module>
    manager.start()
  File "C:\Users\m.waleed\Documents\chess-alpha-zero\src\chess_zero\manager.py",
 line 76, in start
    return uci.start(config)
  File "C:\Users\m.waleed\Documents\chess-alpha-zero\src\chess_zero\play_game\uc
i.py", line 54, in start
    me_player = get_player(config)
  File "C:\Users\m.waleed\Documents\chess-alpha-zero\src\chess_zero\play_game\uc
i.py", line 64, in get_player
    from chess_zero.agent.model_chess import ChessModel
  File "C:\Users\m.waleed\Documents\chess-alpha-zero\src\chess_zero\agent\model_
chess.py", line 11, in <module>
    from keras.engine.topology import Input
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\ke
ras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\ke
ras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\ke
ras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\ke
ras\backend\__init__.py", line 83, in <module>
    from .tensorflow_backend import *
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\ke
ras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\te
nsorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\te
nsorflow\python\__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\te
nsorflow\python\pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\te
nsorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\importlib\__init
__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\te
nsorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\te
nsorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\site-packages\te
nsorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\lib\importlib\__init
__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_probl
ems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**END**
Any assistance would be appreciated.! 
thank you!
