### ISSUE TITLE
I don't undestand anything :/ 

### ISSUE THREAD

**Issue by Carnagal** [Zeta36/chess-alpha-zero#36]
Hello, firstly, I want to say I am really interested by this project even if my knowledge is cleary poor.

So I installed Python for windows, read for days to get a grasp about many things, ok.
Among other things, I have no idea about how to run chess-zero, using UCI with arena is for later...
To be honest, I wonder if I am totally out of the way. 
Last thing I tried is that:
PS C:\Users\xxxx\Projets\chess-alpha-zero-master> python src/chess_zero/run.py play_gui
Traceback (most recent call last):
  File "src/chess_zero/run.py", line 17, in <module>
    from chess_zero import manager
  File "src\chess_zero\manager.py", line 6, in <module>
    from .config import Config
  File "src\chess_zero\config.py", line 2, in <module>
    import chess
ModuleNotFoundError: No module named 'chess'

Is there something I need to download ? 
Thank you for any help in advance.

**Comment by evalon32** [comment]
Did you run pip install -r requirements.txt?

**Comment by Carnagal** [comment]
Yes, I did.

**Comment by brianprichardson** [comment]
pip3 may the needed.  Just "pip" may be pointing to a Python 2 version.  After you install Python 3.6.3, make sure you are running that version.  This Python 2 and 3 stuff is still driving me crazy, especially on Windows.  I gave up and just use venv (virtual environments) on Ubuntu and everything works fine.

**Comment by Akababa** [comment]
Actually would it be possible to remove some of the dependencies? At the very least I think jupyter and ipython can go, and scipy was also giving me a hard time on windows (the one in pip3 doesn't work)

**Comment by brianprichardson** [comment]
As I understand things, the way to remove dependencies is to fork it and remove them yourself (then you can see about merging the changes back).  Also, if you have not already noticed, there are _many_ things that will give you a "hard time" on Windows.

**Comment by Carnagal** [comment]
To begin with, I don't know the system environment variable path ( under windows 10 ) I need to create.

**Comment by Akababa** [comment]
Try cloning it again; the requirements have been pruned.

**Comment by shilet** [comment]
You can try install all requirements one by one. When you don't have nvidia videocard, it cannot install tensorflow-gpu and stops installing the other requirements. You can simply replace tensorflow-gpu by tensorflow. You should install using pip. First find your python installation directory. The pip programme can be found in the directory Scripts. Then you can run (I use cygwin) something like: /cygdrive/f/Python/Python36-64/Scripts/pip.exe install tensorflow
Proceed so for all requirements and test the programme again.

**Comment by shilet** [comment]
You can change the environment variables in Windows via control panel. Just type environment variables in the search box.  (it is located under -> system & security -> system -> advanced system settings). You should set the path to the python install directory and to the Scripts directory.
