### ISSUE TITLE
issue in running sl

### ISSUE THREAD

**Issue by waleedis** [Zeta36/chess-alpha-zero#52]
Facing this error while running run.py sl 
*ERROR*
(cpu_tensor) C:\Users\m.waleed\Documents\chess-alpha-zero>python src/chess_zero/
run.py sl --type mini
2018-01-30 18:12:43,800@chess_zero.manager INFO # config type: mini
['C:\\Users\\m.waleed\\Documents\\chess-alpha-zero\\data\\play_data\\29-1-2018.p
gn']
found 34 games
done reading
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\envs\cpu_tensor\lib\
concurrent\futures\process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "src\chess_zero\worker\sl.py", line 140, in get_buffer
    white_elo, black_elo = int(game.headers["WhiteElo"]), int(game.headers["Blac
kElo"])
KeyError: 'WhiteElo'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/chess_zero/run.py", line 20, in <module>
    manager.start()
  File "src\chess_zero\manager.py", line 73, in start
    return sl.start(config)
  File "src\chess_zero\worker\sl.py", line 25, in start
    return SupervisedLearningWorker(config).start()
  File "src\chess_zero\worker\sl.py", line 58, in start
    env, data = res.result()
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\envs\cpu_tensor\lib\
concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\m.waleed\AppData\Local\Continuum\anaconda3\envs\cpu_tensor\lib\
concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
KeyError: 'WhiteElo'

**END**

**Comment by Shoaibr** [comment]
The problem is your PGN file has some corrupt game data in it which it is not able to parse correctly.
