### ISSUE TITLE
Broken PIPE error when running EVAL phase

### ISSUE THREAD

**Issue by Shoaibr** [Zeta36/chess-alpha-zero#53]
Hi,

I've ran into a crash when running the EVAL phase, initially I have imported the games using the PGN / SL after which i ran the training(OPT) for 1 day, which generated many models under new_generation (around 4.82GB). 

My Config:
- Python 3.6.3
- Keras 2.0.8
- Tensorflow-gpu 1.3.0 (using GPU - Tesla V100-SXM2-16GB)

Command: `python src\chess_zero\run.py eval --type normal`

2018-01-31 11:20:31,206@chess_zero.manager INFO # config type: normal
Using TensorFlow backend.
2018-01-31 11:20:43,486@chess_zero.agent.model_chess DEBUG # loading model from c:\chess-alpha-zero\data\model\model_best_config.json
name: Tesla V100-SXM2-16GB
major: 7 minor: 0 memoryClockRate (GHz) 1.53
pciBusID 0000:00:1e.0
Total memory: 15.87GiB
Free memory: 15.32GiB
2018-01-31 11:20:46.070625: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:976] DMA: 0
2018-01-31 11:20:46.071089: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:986] 0:   Y
2018-01-31 11:20:46.071563: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (
/gpu:0) -> (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:1e.0)
2018-01-31 11:21:00,767@chess_zero.agent.model_chess DEBUG # loaded model digest = 0c379712fcb4204eccea535e5ff099cde78f87037e9805c85d4738bc350adb12
2018-01-31 11:21:00,955@chess_zero.agent.model_chess DEBUG # loading model from c:\chess-alpha-zero\data\model\next_generation\model_20180131-112007.316229\model_config.j
son
2018-01-31 11:21:04,111@chess_zero.agent.model_chess DEBUG # loaded model digest = 401e52dfc80f31e58218c2ab7e28f8bc480c1c9909eb3220c23b7da96d14d668
2018-01-31 11:21:04,111@chess_zero.worker.evaluate DEBUG # start evaluate model c:\chess-alpha-zero\data\model\next_generation\model_20180131-112007.316229
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
2018-01-31 11:24:03,871@chess_zero.worker.evaluate DEBUG # game   1: ng_score=0.0 as black           win_rate=  0.0% r3kb1r/5pp1/4p2p/PQ1pP3/1ppP3B/6N1/3NBPPP/5RK1
2018-01-31 11:24:12,889@chess_zero.worker.evaluate DEBUG # game   2: ng_score=0.0 as black by resign win_rate=  0.0% 2r4r/1p2kpp1/p1p1p1np/8/1P6/P1Q3P1/5PBP/3RR1K1
2018-01-31 11:24:26,526@chess_zero.worker.evaluate DEBUG # game   3: ng_score=0.0 as white by resign win_rate=  0.0% 4R3/2qn1ppk/2p2n1p/p2p1P2/N2P1b2/1P1P3P/P1p3K1/8
2018-01-31 11:24:53,597@chess_zero.worker.evaluate DEBUG # game   4: ng_score=0.0 as white           win_rate=  0.0% 2kr4/p1p2p2/2p5/5bp1/2p5/2P1Qq2/PP1B1n2/R3K2r
2018-01-31 11:25:01,775@chess_zero.worker.evaluate DEBUG # game   5: ng_score=0.5 as black           win_rate= 10.0% 5r2/pN4k1/1b5p/nP1B3p/8/P2P4/2P2PPP/R4RK1
2018-01-31 11:25:43,852@chess_zero.worker.evaluate DEBUG # game   6: ng_score=0.0 as white by resign win_rate=  8.3% 4r1k1/5ppp/p7/1n3P2/1P2r3/6KP/6P1/8
2018-01-31 11:25:46,835@chess_zero.worker.evaluate DEBUG # game   7: ng_score=0.0 as white           win_rate=  7.1% r4rk1/6pp/p1Qb2p1/1p6/3Pp3/4P2P/PP1B3q/R3R2K
2018-01-31 11:26:16,447@chess_zero.worker.evaluate DEBUG # game   8: ng_score=0.0 as black           win_rate=  6.2% 6Q1/7R/8/5p1k/8/8/3p4/6K1
2018-01-31 11:26:24,944@chess_zero.worker.evaluate DEBUG # game   9: ng_score=0.0 as black           win_rate=  5.6% 5Rk1/ppp5/2n2bpQ/3p1p2/3P4/2PB1PN1/PP3P1P/R5K1
2018-01-31 11:26:55,131@chess_zero.worker.evaluate DEBUG # game  10: ng_score=0.0 as black by resign win_rate=  5.0% r4rk1/1p2np1p/p1pP1B2/3p1p2/2P5/1P3N1P/P1QN1PP1/3RR1K
1
2018-01-31 11:27:04,990@chess_zero.worker.evaluate DEBUG # game  11: ng_score=0.0 as white           win_rate=  4.5% 4r1k1/6pp/2p5/3p4/3P4/2R1P2b/6qK/8
2018-01-31 11:27:19,516@chess_zero.worker.evaluate DEBUG # game  12: ng_score=0.0 as white           win_rate=  4.2% r3k3/1b1n1prp/p1p5/1p6/1P1bp1P1/Q7/P3Bq2/5K2
2018-01-31 11:27:50,701@chess_zero.worker.evaluate DEBUG # game  13: ng_score=0.0 as black           win_rate=  3.8% r1b2k1N/p4Qbp/1ppp3q/n4P2/4P3/2NP4/PPP3PP/R4RK1
2018-01-31 11:27:51,332@chess_zero.worker.evaluate DEBUG # game  14: ng_score=1.0 as black           win_rate= 10.7% 5k2/1p4Rp/1p1p1B2/pP6/8/P7/2r3PP/4r1K1
2018-01-31 11:28:41,002@chess_zero.worker.evaluate DEBUG # game  15: ng_score=0.0 as white by resign win_rate= 10.0% 2kr3r/p1p2p2/2p5/5b2/2p3p1/2PnQNq1/PP6/R1BK4
2018-01-31 11:28:54,658@chess_zero.worker.evaluate DEBUG # game  16: ng_score=0.5 as white           win_rate= 12.5% 5Q2/8/5K2/8/8/8/8/1k6
2018-01-31 11:29:13,311@chess_zero.worker.evaluate DEBUG # game  17: ng_score=0.0 as black           win_rate= 11.8% 5Q2/pp2Q3/8/2p4B/1nP2k2/7P/5qPK/8
2018-01-31 11:29:45,672@chess_zero.worker.evaluate DEBUG # game  18: ng_score=0.0 as white by resign win_rate= 11.1% 2r1r1k1/5ppp/p1n5/3b4/P1pP4/2B1P1b1/1P2K1q1/7R
2018-01-31 11:29:55,172@chess_zero.worker.evaluate DEBUG # game  19: ng_score=0.0 as white           win_rate= 10.5% r3r1k1/1p1n2pp/p2Q4/3p1p2/3Pn3/3BPb2/PP3Pq1/R1B1RK2
2018-01-31 11:30:02,172@chess_zero.worker.evaluate DEBUG # game  20: ng_score=0.0 as black by resign win_rate= 10.0% 4r3/8/7Q/p1pk4/5P2/P5K1/6P1/2R4R
2018-01-31 11:30:33,328@chess_zero.worker.evaluate DEBUG # game  21: ng_score=0.0 as black           win_rate=  9.5% 8/1pp1rB2/1b1p2Qk/pP2p3/8/P1PP4/5PPP/R4RK1
2018-01-31 11:30:33,363@chess_zero.worker.evaluate DEBUG # game  22: ng_score=0.0 as white by resign win_rate=  9.1% r1b1k2r/1p3ppp/p1n5/4p3/4n3/2P2Kb1/PP5q/R1BQRB2
2018-01-31 11:31:08,451@chess_zero.worker.evaluate DEBUG # game  23: ng_score=0.0 as black by resign win_rate=  8.7% r2q1rk1/pp1bnNb1/5n1p/2pPN1p1/2P1P3/6BP/PP2BPP1/2RQ1R
K1
2018-01-31 11:31:25,138@chess_zero.worker.evaluate DEBUG # game  24: ng_score=0.0 as white           win_rate=  8.3% 2r2rk1/5p1p/p2p2pP/1p2p1P1/4P3/PP1bBn2/2q5/2K4R
2018-01-31 11:31:25,938@chess_zero.worker.evaluate DEBUG # game  25: ng_score=0.0 as black           win_rate=  8.0% 4k3/p3Q3/1p6/3pR3/bP6/P7/6K1/8
2018-01-31 11:31:25,948@chess_zero.worker.evaluate DEBUG # lose count reach 22 so give up challenge
Traceback (most recent call last):
  File "src\chess_zero\run.py", line 20, in <module>
    manager.start()
  File "src\chess_zero\manager.py", line 70, in start
Exception in thread prediction_worker:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "src\chess_zero\agent\api_chess.py", line 62, in _predict_batch_worker
    while pipe.poll():
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\connection.py", line 257, in poll
    return self._poll(timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\connection.py", line 328, in _poll
    _winapi.PeekNamedPipe(self._handle)[0] != 0):
BrokenPipeError: [WinError 109] The pipe has been ended

    return evaluate.start(config)
  File "src\chess_zero\worker\evaluate.py", line 22, in start
    return EvaluateWorker(config).start()
  File "src\chess_zero\worker\evaluate.py", line 59, in start
    self.move_model(model_dir)
  File "src\chess_zero\worker\evaluate.py", line 111, in move_model
    new_dir = os.path.join(rc.next_generation_model_dir, "copies", model_dir.name)
AttributeError: 'str' object has no attribute 'name'
Exception in thread prediction_worker:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "src\chess_zero\agent\api_chess.py", line 62, in _predict_batch_worker
    while pipe.poll():
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\connection.py", line 257, in poll
    return self._poll(timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\connection.py", line 328, in _poll
    _winapi.PeekNamedPipe(self._handle)[0] != 0):
BrokenPipeError: [WinError 109] The pipe has been ended

Thanks

**Comment by jimmyai** [comment]
I am also facing this issue and have tested this on four different machines (windows/linux). 
I think while pipe closing its resources it generate broken pipe error.

Is the eval phase broken?

**Comment by Akababa** [comment]
You can ignore it, it just happens when the program exits (after "lose count reach 22 so give up challenge").

**Comment by dandrademv** [comment]
Did anyone ever find a solution to this? I am still stuck at this step.

**Comment by dandrademv** [comment]
> You can ignore it, it just happens when the program exits (after "lose count reach 22 so give up challenge").

I ignored it, but nothing happens. It doesn't evaluate a single game.
