### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 1715509415** [Zeta36/chess-alpha-zero#54]
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 9761: illegal multibyte sequence

**Comment by 1715509415** [comment]
why? I can't find a solution.Two days, I can't do it
PS C:\Users\Administrator> pip install python-chess
Collecting python-chess
  Using cached python-chess-0.22.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-iw3dr26g\python-chess\setup.py", line 84, in <module>
        long_description=read_description(),
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-iw3dr26g\python-chess\setup.py", line 33, in read_description

        description = open(os.path.join(os.path.dirname(__file__), "README.rst")).read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 9761: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-iw3dr26g\p
ython-chess\
PS C:\Users\Administrator>

**Comment by Akababa** [comment]
Try `pip install --upgrade --force-reinstall python-chess`
If it still doesn't work open an issue in https://github.com/niklasf/python-chess/issues
