### ISSUE TITLE
ImportError: cannot import name 'multiarray'

### ISSUE THREAD

**Issue by byeung888** [Zeta36/chess-alpha-zero#56]
I am getting an error.  I have ran the requirements without issues and I am running it with Python 3.6 on Ubuntu 16.04 LTS.  What is wrong?

$ python3.6 src/chess_zero/run.py sl
Traceback (most recent call last):
  File "src/chess_zero/run.py", line 19, in <module>
    from chess_zero import manager
  File "src/chess_zero/manager.py", line 10, in <module>
    from .config import Config
  File "src/chess_zero/config.py", line 6, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'

**Comment by Akababa** [comment]
It looks like you can't import numpy.. try reinstalling the package?
