### ISSUE TITLE
pyperclip access denied error on Windows 10

### ISSUE THREAD

**Issue by hros** [Zeta36/chess-alpha-zero#61]
When running: python src/chess_zero/run.py self
On Windows 10 with up-to-date anaconda-python-3.6 with all requirements installed, I get the following error with pyperclip:

> Traceback (most recent call last):
>   File "src/chess_zero/run.py", line 20, in <module>
>     manager.start()
>   File "src\chess_zero\manager.py", line 64, in start
>     return self_play.start(config)
>   File "src\chess_zero\worker\self_play.py", line 25, in start
>     return SelfPlayWorker(config).start()
>   File "src\chess_zero\worker\self_play.py", line 69, in start
>     pretty_print(env, ("current_model", "current_model"))
>   File "src\chess_zero\lib\data_helper.py", line 26, in pretty_print
>     pyperclip.copy(env.board.fen())
>   File "C:\Users\user\Anaconda3\lib\site-packages\pyperclip\__init__.py", line 574, in lazy_load_stub_copy
>     return copy(text)
>   File "C:\Users\user\Anaconda3\lib\site-packages\pyperclip\__init__.py", line 416, in copy_windows
>     with clipboard(hwnd):
>   File "C:\Users\user\Anaconda3\lib\contextlib.py", line 81, in __enter__
>     return next(self.gen)
>   File "C:\Users\user\Anaconda3\lib\site-packages\pyperclip\__init__.py", line 400, in clipboard
>     raise PyperclipWindowsException("Error calling OpenClipboard")
> pyperclip.PyperclipWindowsException: Error calling OpenClipboard ([WinError 5] Access is denied.)
> Exception in thread prediction_worker:
> Traceback (most recent call last):
>   File "C:\Users\user\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\Users\user\Anaconda3\lib\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "src\chess_zero\agent\api_chess.py", line 62, in _predict_batch_worker
>     while pipe.poll():
>   File "C:\Users\user\Anaconda3\lib\multiprocessing\connection.py", line 257, in poll
>     return self._poll(timeout)
>   File "C:\Users\user\Anaconda3\lib\multiprocessing\connection.py", line 328, in _poll
>     _winapi.PeekNamedPipe(self._handle)[0] != 0):
> BrokenPipeError: [WinError 109] The pipe has been ended
> 

When testing pyperclip functionality with the same string in a python shell it seems to work correctly, so my assumption is that it has to do with the multiprocessing environment

**Comment by Akababa** [comment]
Is there any output before this error?

**Comment by hros** [comment]
reran it
here is the entire output:

```
>python src/chess_zero/run.py self

2018-03-06 16:09:12,264@chess_zero.manager INFO # config type: mini
Using TensorFlow backend.
2018-03-06 16:09:16,399@chess_zero.agent.model_chess DEBUG # loading model from C:\Users\user\chess-alpha-zero\data\model\model_best_config.json
2018-03-06 16:09:22,257@chess_zero.agent.model_chess DEBUG # loaded model digest = ad5a6bbf93ca8130b9130f32d3d44c3de2b5d92f80d64e9dd1f40d6d1edd7b24
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
game   1 time=1449.9s halfmoves=128 Winner.black
Traceback (most recent call last):
  File "src/chess_zero/run.py", line 20, in <module>
    manager.start()
  File "src\chess_zero\manager.py", line 64, in start
    return self_play.start(config)
  File "src\chess_zero\worker\self_play.py", line 25, in start
    return SelfPlayWorker(config).start()
  File "src\chess_zero\worker\self_play.py", line 69, in start
    pretty_print(env, ("current_model", "current_model"))
  File "src\chess_zero\lib\data_helper.py", line 26, in pretty_print
    pyperclip.copy(env.board.fen())
  File "C:\Users\user\Anaconda3\lib\site-packages\pyperclip\__init__.py", line 574, in lazy_load_stub_copy
    return copy(text)
  File "C:\Users\user\Anaconda3\lib\site-packages\pyperclip\__init__.py", line 416, in copy_windows
    with clipboard(hwnd):
  File "C:\Users\user\Anaconda3\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\user\Anaconda3\lib\site-packages\pyperclip\__init__.py", line 400, in clipboard
    raise PyperclipWindowsException("Error calling OpenClipboard")
pyperclip.PyperclipWindowsException: Error calling OpenClipboard ([WinError 5] Access is denied.)
```

**Comment by Akababa** [comment]
I'm not sure how to fix your clipboard permissions, but it's probably safe to just delete all the "pyperclip" lines.
