### ISSUE TITLE
Error during supervised learning

### ISSUE THREAD

**Issue by shine** [Zeta36/chess-alpha-zero#65]
I'm trying to teach model by set of ~4000 games in PGN file. I'm using Python 3.6.3 and Tensorflow without GPU. Here is error traceback:
`
puser@vmi148103:~/chess-alpha-zero$ python3 src/chess_zero/run.py sl
2018-03-09 19:48:42,418@chess_zero.manager INFO # config type: mini
['/home/puser/chess-alpha-zero/data/play_data/Ivanchuk.pgn']
found 4033 games
done reading
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "src/chess_zero/worker/sl.py", line 140, in get_buffer
    white_elo, black_elo = int(game.headers["WhiteElo"]), int(game.headers["BlackElo"])
ValueError: invalid literal for int() with base 10: ''
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/chess_zero/run.py", line 20, in <module>
    manager.start()
  File "src/chess_zero/manager.py", line 73, in start
    return sl.start(config)
  File "src/chess_zero/worker/sl.py", line 25, in start
    return SupervisedLearningWorker(config).start()
  File "src/chess_zero/worker/sl.py", line 58, in start
    env, data = res.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: invalid literal for int() with base 10: ''
`
Any ideas what can be wrong here?

**Comment by Akababa** [comment]
it appears your PGN file has a non-digit in one of WhiteELO/BlackELO tags.
